### ISSUE TITLE
locale load can't be bundled anymore

### ISSUE THREAD

**Issue by retorquere** [inukshuk/edtf.js#40]
This snippet

```
const load = (locale) =>
  JSON.parse(fs.readFileSync(new URL(`../locale-data/${locale}.json`, (typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.cjs', document.baseURI).href)))));
```

can't be bundled. I can work around it by using a compile-time patch, but what is the benefit of loading this way over a `require('../locale-data/en.json')`?

**Comment by inukshuk** [comment]
What prompted the change was actually that you were confused by the mixed use of CommonJS and ES modules -- we used CJS to load the locale data as a convenience because ES modules didn't support loading JSON. It looks like [import assertions](https://nodejs.org/docs/latest-v16.x/api/esm.html#import-assertions) now work in Node.js v16 so I think we could switch to those instead.

**Comment by inukshuk** [comment]
Switched to import assertions in 4.3.0

**Comment by inukshuk** [comment]
It turns out the support in Rollup isn't great; there's a plugin, but there are complications if you (or a dependency) also requires JSON files. I'll revert back to using CommonJS for the locale data until Rollup has built-in support for import assertions.

**Comment by retorquere** [comment]
esbuild has so far been able to compile everything I could throw at it (with the addition of some plugins).
